### ISSUE TITLE
[FEATURE] Compiler and runtime docker for aarch64

### ISSUE THREAD

**Issue by bonifaido** [eunomia-bpf/eunomia-bpf#124]
**Is your feature request related to a problem? Please describe.**

I saw the examples are running a CLI tool called `ebpm`:

```bash
# use docker to compile the ebpf code to a file `package.json`
$ docker run -it -v /path/to/repo/hello:/src yunwei37/ebpm:latest
```

I tried this on my aarch64 machine, but the docker image is built for x86 only. I haven't find the source code for this, just a repo, called ebpm, without the code of the CLI. Can you help me how to make this work on ARM?

**Comment by yunwei37** [comment]
I will do this right away, thanks for reminding me!

By the way, the name `yunwei37/ebpm:latest` would be depreciated in the future, see https://github.com/eunomia-bpf/eunomia-bpf/issues/42

**Comment by yunwei37** [comment]
I have create a new docker, you may try it : )

Build the eBPF program example:

```sh
cd examples/bpftools/sigsnoop
sudo docker run -it -v `pwd`/:/src/ ghcr.io/eunomia-bpf/ecc-`uname -m`:latest
```

Run the eBPF program:

```sh
wget https://github.com/eunomia-bpf/eunomia-bpf/releases/download/v0.3.2/ecli-aarch64 && chmod +x ./ecli
sudo ./ecli package.json
```

We use `ecc` for compile and `ecli` for running programs. You can build it from this repo, see https://github.com/eunomia-bpf/eunomia-bpf/tree/v0.3.2#build-or-install-the-project

**Comment by yunwei37** [comment]
A runtime docker for aarch64 will be added in https://github.com/eunomia-bpf/eunomia-bpf/issues/42

**Comment by bonifaido** [comment]
Thank you for the quick turnaround, works nicely!
