### ISSUE TITLE
[FEATURE] Integrating with BTFGen and BTFHub together in toolchain

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/eunomia-bpf#125]
**Is your feature request related to a problem? Please describe.**

> CO-RE requires to have BTF information describing the types of the
> kernel in order to perform the relocations. This is usually provided by
> the kernel itself when it's configured with CONFIG_DEBUG_INFO_BTF.
> However, this configuration is not enabled in all the distributions and
> it's not available on kernels before 5.12.
>
> It's possible to use CO-RE in kernels without CONFIG_DEBUG_INFO_BTF
> support by providing the BTF information from an external source.
> BTFHub[0] contains BTF files to each released kernel not supporting BTF,
> for the most popular distributions.

>Providing this BTF file for a given kernel has some challenges: 1. Each
> BTF file is a few MBs big, then it's not possible to ship the eBPF
> program with all the BTF files needed to run in different kernels. (The
> BTF files will be in the order of GBs if you want to support a high
> number of kernels) 2. Downloading the BTF file for the current kernel at
> runtime delays the start of the program and it's not always possible to
> reach an external host to download such a file.

> Providing the BTF file with the information about all the data types of
> the kernel for running an eBPF program is an overkill in many of the
> cases. Usually the eBPF programs access only some kernel fields.
>
> This series implements BTFGen support in bpftool by exposing some of the
> internal libbpf's APIs to it.
>
> This idea was discussed during the "Towards truly portable eBPF"[1]
> presentation at Linux Plumbers 2021.
> 
> There is a good example[2] on how to use BTFGen and BTFHub together
> to generate multiple BTF files, to each existing/supported kernel,
> tailored to one application. For example: a complex bpf object might
> support nearly 400 kernels by having BTF files summing only 1.5 MB.
>
> [0]: https://github.com/aquasecurity/btfhub/
> [1]: https://www.youtube.com/watch?v=igJLKyP1lFk&t=2418s
> [2]: https://github.com/aquasecurity/btfhub/tree/main/tools

**Describe the solution you'd like**

When a user start compile with btfgen enable:

```c
ecc opensnoop.bpf.c opensnoop.h --btfgen
```

1. The compiler should check whether btfhub archive exists in EUNOMIA_HOME (~/.eunomia), if not, download from git repo；
2. after compiling BPF program success, use bpftool to generate smaller BTF info, compress them and encode in JSON; (Is it any better ways?)
   - https://github.com/aquasecurity/btfhub/blob/main/docs/generating-tailored-btfs.md
3. when running the BPF program, the bpf-loader should decompress them, select the right version and use it.

**Provide usage examples**

### for the compiler:

Add an option in ecc to compile ebpf programs with btfgen and btfhub, for example:

```c
ecc opensnoop.bpf.c opensnoop.h --btfgen
```

### for the runtime:

Runtime will not change. Use the JSON for running is OK.

```bash
sudo ./ecli run package.json
```

**Additional context**

- https://lore.kernel.org/bpf/CAEf4BzZw2RBPSxE0j8uQd8-75qOfq=iPnhB73ONErsHYUaF+pg@mail.gmail.com/T/
- https://kinvolk.io/blog/2022/03/btfgen-one-step-closer-to-truly-portable-ebpf-programs/

**Comment by Mr-dot-lu** [comment]
btfhub is not the perfect solution for eBPF portability, and it comes with high management costs. The eBPF software package should be portable and self-descriptive.
The information includes the supported kernel versions, dependent BTF files, and attached object information.

Therefore, it is a good idea to add BTF files to the eBPF software package to allow earlier kernel versions to use CO-RE capabilities and avoid BTF management costs.
In addition, the eBPF software package can be divided into two parts: package description and software compression. For details, see the RPM specifications.

**Comment by yunwei37** [comment]
Thank you very much!

Maybe we can take a look at https://github.com/l3af-project/l3afd

**Comment by yunwei37** [comment]
Please add a document and an end to end CI test to cover this feature.

**Comment by yunwei37** [comment]
fix now.
