### ISSUE TITLE
some issue when i test demo

### ISSUE THREAD

**Issue by wanqingYuan** [eunomia-bpf/eunomia-bpf#13]
```shell
$ wget https://aka.pw/bpf-ecli -O ecli && chmod +x ./ecli    # 下载安装 ecli
$ docker run -it -v ~/ebpf:/src yunwei37/ebpm # 使用容器进行编译，生成一个 package.json 文件，是已经编译好的代码
$ sudo ./ecli run package.json                # 运行 ebpf 程序
```
<img width="413" alt="bd7a37cacf55474219a0f89b93dcc99" src="https://user-images.githubusercontent.com/61040457/188345120-6b304a17-2b3e-4a46-b87e-d10e1ddd0618.png">
出现 aka.pw 这个域名找不到，但是如果使用阿里云服务器就可以解析 aka.pw这个域名

另外，ecli这个二进制文件依赖的是gcc-11版本，阿里云镜像中最高到gcc-10版本，可以添加腾讯云镜像 mirrors.cloud.tencent.com 
<img width="565" alt="cfd056147775b35ff9fcd7f27e4c2f3" src="https://user-images.githubusercontent.com/61040457/188345570-1761a46a-b83f-4c29-9e9a-0b50adca13be.png">
<img width="298" alt="1358c97b044816f79ec5b19a84ad772" src="https://user-images.githubusercontent.com/61040457/188345584-c3ae4cf7-0d93-4c22-8055-23386ebcbb76.png">

**Comment by yunwei37** [comment]
非常感谢您！
- 我把 gcc-11 替换成了 gcc-9, 这样应该出现 libstdc++ 的兼容性问题的情况会少一些
- aka.pw 这个域名无法访问的话，直接使用 github release 也是可以的，具体问题我还在排查（我想想怎么办...）
