### ISSUE TITLE
[FEATURE] nix and devenv support

### ISSUE THREAD

**Issue by ocfox** [eunomia-bpf/eunomia-bpf#158]
Add support for nix flake and devenv, including packages ecli, ecc, and devShell (based on devenv).
Once done, you will be able to:
1. Use `nix develop` to enter the development environment, which contains all the dependencies needed for the project and packages ecc ecli etc. (maybe add an option for this? Add it to the PATH or not.)
2. [git pre-commit hooks](https://devenv.sh/pre-commit-hooks/): approach for integrating your linters and formatters. It will auto-check and format the cpp and rust code according to the requirements of the repository before the git commit.
3. A development environment containing minimal ebpf with eunomia-bpf, on any machine with nix installed Use ```nix develop github:eunomia-bpf/eunomia-bpf#ebpf-dev``` to access it. This will be a great convenience for developers using eunomia-bpf for ebpf development.
4. manual/documents in shell, use `help` in this dev shell will get develop help and other documents.
5. templates: run `nix flake init --template github:eunomia-bpf/eunomia-bpf#templates` will create a flake.nix template containing the devshell and minimal ebpf, run `nix run .#templates-package` in the directory will build and run this ebpf program.

**Comment by oluceps** [comment]
At present flake needs to with extra arguments to build eunimia-bpf e.g. `nix build '.?submodules=1#ecc'` because of using submodules, will it affect the next step of integrating? or any idea for solving this?

Btw any clues for clearing dup reference messages above? Which appears after a few squashes & pushes. O﹏o

**Comment by ocfox** [comment]
We can open a new repository and then build these submodules separately as buildinputs.

**Comment by Officeyutong** [comment]
What's going on now

**Comment by oluceps** [comment]
> At present flake needs to with extra arguments to build eunimia-bpf ...

Solved on https://github.com/eunomia-bpf/eunomia-bpf/commit/c3347106496ecc2e286a240adf613057bd889419.

> What's going on now


- [x] Use nix develop to enter the development environment, which contains all the dependencies needed for the project and packages ecc ecli etc.

  Try it with run `nix develop github:eunomia-bpf/eunomia-bpf/flake-devenv#devShells.x86_64-linux.ebpf-dev`
- [x] Integrate Git pre-commit hooks for linters and formatters, automatically checking and formatting the code.

  Waiting for further integration with devenv.
- [ ] A development environment containing minimal ebpf with eunomia-bpf, on any machine with nix installed Use nix develop github:eunomia-bpf/eunomia-bpf#ebpf-dev to access it. 
  
  Not quite understand.. Is this as well as 1st point?
- [ ] Use help in the development Shell to access development help and other documents.
- [ ] Run nix flake init --template github:eunomia-bpf/eunomia-bpf#templates to create a flake.nix template containing the devshell and minimal eBPF. Use nix run .#templates-package in the directory to build and run the eBPF program.

**Comment by yunwei37** [comment]
Is there any improvement now on this issue?

**Comment by oluceps** [comment]
Maybe it's time to draft a pr now. Most goals of this issue had been implemented, and the branch diverged from master for too long.

**Comment by yunwei37** [comment]
Fixed?

**Comment by oluceps** [comment]
Solved.
