### ISSUE TITLE
[FEATURE] add project templates for starters

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/eunomia-bpf#176]
add github project template for building projects, include go, rust and c. It would be like:

- a make file for build the project in one command
- a docker file
- a github action
- all necessary dependences

See https://github.com/eunomia-bpf/eunomia-template for an example.

And see https://github.com/linuxkerneltravel/lmp/issues/439 for more details.

**Comment by yunwei37** [comment]
Similar project:

- https://github.com/aya-rs/aya-template
- https://github.com/Esonhugh/ebpf_cilium_starter

**Comment by yunwei37** [comment]
Step to do this:
1.  Sync the eunomia-template with the latest toolchain. The old eunomia-template project is out of date, it needs to be tested and fixed.
2. Add a libbpf-starter-template repo in eunomia org. 
3. Add a cillium-starter-template repo in eunomia org.
4. Add a libbpf-rs-starter-template repo in our project.

**Comment by ocfox** [comment]
Done in
https://github.com/eunomia-bpf/eunomia-template
https://github.com/eunomia-bpf/libbpf-starter-template
https://github.com/eunomia-bpf/cilium-ebpf-starter-template
https://github.com/eunomia-bpf/libbpf-rs-starter-template
