### ISSUE TITLE
ubuntu本地编译ecc没生成可执行文件，请帮忙确认一下原因，谢谢

### ISSUE THREAD

**Issue by 3edc2wsx** [eunomia-bpf/eunomia-bpf#189]
一、操作系统环境：
root@ubuntu-server:~/eunomia-bpf# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.10"
NAME="Ubuntu"
VERSION_ID="22.10"
VERSION="22.10 (Kinetic Kudu)"
VERSION_CODENAME=kinetic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=kinetic
LOGO=ubuntu-logo

二、编译步骤：
完全按照指导编译https://github.com/eunomia-bpf/eunomia-bpf/blob/master/documents/build.md。
鉴于makefile中没编译wasm-runtime，跳过build wasm lib步骤。
完整步骤是：
apt install clang libelf1 libelf-dev zlib1g-dev
curl https://sh.rustup.rs -sSf | sh -s
git submodule update --init --recursive --remote     
make bpf-loader                           
make ecli
make ecc

三、编译结果：
root@ubuntu-server:~/eunomia-bpf# find -name ecc
./documents/src/ecc           
root@ubuntu-server:~/eunomia-bpf# find -name ecli
./documents/src/ecli
./ecli                                     
./ecli/target/release/ecli      ------ecli生成可执行文件，ecc没有

四、make ecc回显：
root@ubuntu-server:~/eunomia-bpf# make ecc
make -C compiler -no-pie
make[1]: Entering directory '/root/eunomia-bpf/compiler'
make -C /root/eunomia-bpf/third_party/bpftool/src
...                        libbfd: [ on  ]
...               clang-bpf-co-re: [ on  ]
...                          llvm: [ on  ]
...                        libcap: [ OFF ]
printf '  %-9s%s\n' LINK bpftool;cc -O2 -W -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wold-style-definition -Wpacked -Wredundant-decls -Wshadow -Wstrict-prototypes -Wswitch-default -Wundef -Wwrite-strings -DPACKAGE='"bpftool"' -D__EXPORTED_HEADERS__ -I. -I/root/eunomia-bpf/third_party/bpftool/src/libbpf/include -I/root/eunomia-bpf/third_party/bpftool/src/kernel/bpf/ -I/root/eunomia-bpf/third_party/bpftool/include -I/root/eunomia-bpf/third_party/bpftool/include/uapi -DHAVE_LLVM_SUPPORT -I/usr/lib/llvm-15/include  -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -lLLVM-15 -L/usr/lib/llvm-15/lib  btf.o btf_dumper.o cfg.o cgroup.o common.o feature.o gen.o iter.o jit_disasm.o json_writer.o link.o main.o map.o map_perf_ring.o net.o netlink_dumper.o perf.o prog.o struct_ops.o tracelog.o xlated_dumper.o disasm.o /root/eunomia-bpf/third_party/bpftool/src/libbpf/libbpf.a -lelf -lz -lLLVM-15 -o bpftool
rm -rf workspace
mkdir -p workspace/bin workspace/include
cp /root/eunomia-bpf/third_party/bpftool/src/bpftool workspace/bin/bpftool
cp -r /root/eunomia-bpf/third_party/bpftool/src/libbpf/include/bpf workspace/include/bpf
cp -r ../third_party/vmlinux workspace/include/vmlinux
cd cmd && cargo build --release
cp cmd/target/release/ecc workspace/bin/ecc
make[1]: Leaving directory '/root/eunomia-bpf/compiler'

**Comment by ocfox** [comment]
>  cmd/target/release/ecc
>  workspace/bin/ecc
Is there no such file in these two directories?

**Comment by 3edc2wsx** [comment]
编译完成后没有这两个目录，不知是否和我修改Makefile有关。
原Makefile编译报错1，我修改了Makefile。
原makefile是：
ecc: ## build the core library for eunomia-bpf
        make -C compiler
修改后是：
ecc: ## build the core library for eunomia-bpf
        make -C compiler -no-pie

报错1：
root@ubuntu-server:~/eunomia-bpf# make ecc
make -C compiler
make[1]: Entering directory '/root/eunomia-bpf/compiler'
make -C /root/eunomia-bpf/third_party/bpftool/src
...                        libbfd: [ on  ]
...               clang-bpf-co-re: [ on  ]
...                          llvm: [ on  ]
...                        libcap: [ OFF ]
  LINK     bpftool
/usr/bin/ld: btf.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:233: bpftool] Error 1
make[1]: *** [Makefile:63: /root/eunomia-bpf/third_party/bpftool/src/bpftool] Error 2
make[1]: Leaving directory '/root/eunomia-bpf/compiler'
make: *** [Makefile:45: ecc] Error 2

**Comment by ocfox** [comment]
try `make ecc EXTRA_CFLAGS=-no-pie`

**Comment by 3edc2wsx** [comment]
可以了 谢谢
