### ISSUE TITLE
eunomia-exporter stop program sometime is invalid

### ISSUE THREAD

**Issue by wanqingYuan** [eunomia-bpf/eunomia-bpf#19]
**Describe the bug**
当我启动exporter后，首先删除当前挂载的所有bpf程序，然后使用相同的请求数据(name等参数均相同)再次start一个bpf程序，程序启动后再次停止该程序时失败。运行结果如下图所示：

![e1c93830dcf9fe8314159585a32324d](https://user-images.githubusercontent.com/61040457/190328131-9e60aff6-bd53-4ae3-94ce-7f8b4e5d577c.png)

根据 list 返回结果 [[1:"opensnoopy"]] ，发现返回结果是个嵌套数组，而不是一个非嵌套的json数组，因此猜测可能是因为参数相同导致list成为一个嵌套数组，从而导致 stop 时无法找到对应 id

**Comment by yunwei37** [comment]
这个问题其实是没有使用最新的 release 造成的，所以应该已经解决了。其实我认为我现在需要一个自动构建，测试之后并且发布到  release 的 CI？
