### ISSUE TITLE
draft OSPP project

### ISSUE THREAD

**Issue by Officeyutong** [eunomia-bpf/eunomia-bpf#204]
此处讨论 OSPP 项目的草案（未经审核，以ospp 官方通过的项目为准），用中文即可。

OSPP 需要的项目格式可以参考其他项目，见https://summer-ospp.ac.cn/org/projectlist?lang=zh&pageNum=1&pageSize=50&programName=，
或者：
- https://mp.weixin.qq.com/s/2kPKjCq2t0jHnNPp5fv0Fg
- https://summer-ospp.ac.cn/help/community/

**Comment by Officeyutong** [comment]
#  浏览器中的可视化 ebpf 工具编译运行环境类库:

在浏览器中也可以轻松利用现有 bcc/libbpf/bpftrace 工具代码，执行 ebpf 的数据处理、编译、加载控制工作，进一步降低学习和使用门槛，减少编译不确定性，降低简单工具的可视化，和图形界面的开发和使用难度，只需要一个数 mb 的小二进制运行时，即可在网页中完成一系列操作，本地不需要安装 prom/grafana，不需要容器，不需要任何编译器安装，打开网页即可使用；可以像打开网页一样轻松通过 URL 安装任意插件并获取可视化结果，可以修改代码后一键重新编译运行，支持直接运行 bcc 的所有工具（由 ebpf+浏览器里面的wasm虚拟机提供支持，所有的编译进程都放在浏览器里面，本质上是一个重前端的应用）

**Comment by Officeyutong** [comment]
# 搭建性能分析与 eBPF 代码生成的 AIGC 辅助工具

https://github.com/oscomp/proj204-eBPF-AIGC

TODO: 整理成OSPP的格式

**Comment by ocfox** [comment]
# Developing a CPU/Memory/IO Monitoring Tool based on eBPF

## Tech Tags
`Linux` `eBPF` `C/C++` `Monitoring`

## Language
中文&English

## Difficulty
Advanced

## Mentor
ocfox ospp@ocfox.me

## Description
This project aims to develop a monitoring tool using eBPF technology that can monitor CPU, memory, and IO usage on Linux systems. The tool should be able to collect and display real-time data about these metrics, allowing system administrators to identify and diagnose performance issues quickly.

## Output Requirements
- A fully functional monitoring tool that uses eBPF technology to collect and display real-time data about CPU, memory, and IO usage on Linux systems.
- Provide detailed documentation
- Provide a front-end interface to display monitoring results (Optional)

## Technical Requirements
- Good knowledge of C/C++ programming language and Linux system
- Familiarity with eBPF technology
- Have a passion and strong interest in open source

## Project Repository

https://github.com/eunomia-bpf/eunotrac


# 开发基于eBPF的CPU/内存/IO监测工具

## 开源协议
MIT
## 技术领域
`Linux` `eBPF` `C/C++` `Monitoring`
## 难度
进阶
## 导师
ocfox ospp@ocfox.me
## 项目简介
本项目旨在使用ebpf技术实现一个简单易用的Linux系统监测工具，支持实时监控CPU、内存和IO使用情况，并将数据可视化展示(可选），方便用户进行性能优化和故障排查。

## 项目产出要求
- 实现一个基于ebpf技术的Linux系统监测工具，支持实时监测CPU使用率、内存使用情况和IO使用情况
- 提供详细的文档和使用说明
- 提供前端界面展示监测结果（可选）

## 项目技术要求
- 熟悉Linux系统监测和性能优化相关知识
- 掌握C语言编程技术和ebpf技术
- 对开源有热情

https://github.com/eunomia-bpf/eunotrac

**Comment by ocfox** [comment]
# Developing Frontend for ecli server

## Tech Tags
`Linux` `Web` `Rust`

## Language
中文&English

## Difficulty
Advanced

## Mentor
ocfox ospp@ocfox.me

## Description
The goal of this project is to add a frontend to the existing ecli server tool. The frontend should allow the user to upload WASM and JSON files from the web interface and execute them on a target host. The output generated on the target host should be returned and visualized on the frontend.

## Output Requirements
- A web frontend for ecli server that allows users to upload WASM and JSON files and execute them on a target host.
- The frontend should be able to display the output generated on the target host in a visual manner.
- The frontend should be designed to be simple and easy to use.
- A demo that shows how to use the frontend to upload WASM and JSON files and execute them on a target host. (Optional)
- Support for multiple target hosts, the user could choose a target host. (Optional)

## Technical Requirements
- Good knowledge of Rust programming language and Linux system
- Familiar with front-end development
- Have a passion and strong interest in open source

## Project Repository
https://github.com/eunomia-bpf/eunomia-bpf


# 开发ecli服务器的前端

## 开源协议
MIT

## 技术领域
`Linux` `Web` `Rust`

## 难度
进阶

## 导师
ocfox ospp@ocfox.me

## 项目简介
这个项目的目标是为现有的ecli服务器工具添加一个前端。前端应该允许用户从Web界面上传WASM和JSON文件，并在目标主机上执行这些文件。在目标主机上产生的输出应该在前端返回并可视化。

## 项目产出要求
- ecli服务器的web前端，允许用户上传WASM和JSON文件，并在目标主机上执行。
- 以可视化的方式显示在目标主机上生成的输出。
- 演示如何使用前端上传WASM和JSON文件并在目标主机上执行它们。(可选)
- 支持多个目标主机，用户可以选择一个目标主机。(可选)

## 项目技术要求
- 对Rust编程语言和Linux系统了解
- 熟悉前端开发
- 对开源有热情和强烈的兴趣

## 项目仓库
https://github.com/eunomia-bpf/eunomia-bpf

**Comment by Officeyutong** [comment]
Already published
