### ISSUE TITLE
[BUG] ecli failed to deal BPF_MAP_TYPE_STACK_TRACE

### ISSUE THREAD

**Issue by try-agaaain** [eunomia-bpf/eunomia-bpf#210]
**Describe the bug**
I am writing a memleak tool, this tool needs to use BPF_MAP_TYPE_STACK_TRACE to store information related to user stack or kernel stack , after ecc compile to get package.json, when executed with eccli, the following error occurs:
```console
libbpf: map 'stack_traces': failed to create: Invalid argument(-22)
libbpf: failed to load object 'memleak_bpf*�'
Error: BpfError("Failed to load or attach bpf program: Failed to load bpf object")
```

**To Reproduce**

1. get the bpf code: [memleak.bpf.c](https://github.com/try-agaaain/bpf-developer-tutorial/blob/main/src/16-memleak/memleak.bpf.c) and [memleak.h](https://github.com/try-agaaain/bpf-developer-tutorial/blob/main/src/16-memleak/memleak.h)
2. use ecc to compile `ecc memleak.bpf.c memleak.h`
3. use ecli to run `sudo ecli run package.json`
4. error occur.

**OS Info**
```console
$ uname -a
Linux todo-amd64 5.19.0-40-generic #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Officeyutong** [comment]
Try to change the declaration of your map to :
```c
struct {
    __uint(type, BPF_MAP_TYPE_STACK_TRACE);
    __uint(max_entries, 1024);
    __uint(key_size, sizeof(uint32_t));
    __uint(value_size, sizeof(uint64_t) * 16);
} stack_traces SEC(".maps");
```

**Comment by Officeyutong** [comment]
But notice that, seems there are still some errors with your ebpf program. libbpf reported the following logs when loading that:
```console
libbpf: prog 'tracepoint_kfree': BPF program load failed: Invalid argument
libbpf: prog 'tracepoint_kfree': -- BEGIN PROG LOAD LOG --
R1 type=ctx expected=fp
; return gen_free_enter((struct pt_regs*)args, (void*)args->ptr);
0: <invalid CO-RE relocation>
failed to resolve CO-RE relocation <byte_off> [95] struct trace_event_raw_kmem_free.ptr (0:2 @ offset 16)
processed 1 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
-- END PROG LOAD LOG --
libbpf: prog 'tracepoint_kfree': failed to load: -22
```

I haven't find the declaration of `trace_event_raw_kmem_free` anywhere. I also find that when using `tracepoint/kmem/free`, we should accept an argument of type `struct trace_event_raw_kfree *`. Please check your code once more.

**Comment by Officeyutong** [comment]
Seems you are using losts of `uprobe`s (for tracking `malloc`, `calloc`, and so on). Such probes should either be described together along with a executable name, or be specially attached. Currently `bpf-loader` (`ecli`) does not support this kind of special attaching. Please track #218 for more information

**Comment by yunwei37** [comment]
Duplicated with #242
