### ISSUE TITLE
[FEATURE] Support more attaching types for program

### ISSUE THREAD

**Issue by Officeyutong** [eunomia-bpf/eunomia-bpf#218]
Currently, we only support eBPF programs that can be auto-attached and very few other attach types (tc only). We need to implement more attach types.

**Comment by yunwei37** [comment]
Give a design document before you start working on this.

**Comment by benjaminchang123** [comment]
Is uprobe not supported yet ? I tried using version 1.0.38, but found that there were still some limitations when binding uprobe.  https://github.com/eunomia-bpf/eunomia-bpf/issues/210#issuecomment-1536563274   @Officeyutong @yunwei37

**Comment by yunwei37** [comment]
it should be supported. Let me check

**Comment by benjaminchang123** [comment]
In version 1.0.38, the binding of uprobe still requires writing the full path in the kernel code xxxx.bpf.c, and then having libbpf complete the auto-attach. It seems that ecli has not yet implemented the function of manually attach through bpf_program__attach_uprobe_opts and passing parameters from the user space.

**Comment by benjaminchang123** [comment]
Furthermore, xdp/tc can only complete the attach process by hardcoding the attach information in the code. For example: 

/// @ifindex 1 
/// @flags 0
/// @xdpopts {"old_prog_fd":0}. 
https://github.com/eunomia-bpf/eunomia-bpf/blob/v1.0.38/bpf-loader-rs/bpf-loader-lib/assets/simple_prog_5/test.bpf.c 

There are some limitations to this approach. Why not use ecli to dynamically pass parameters for a complete attach instead?
