### ISSUE TITLE
[FEATURE]  怎么使用到android上？

### ISSUE THREAD

**Issue by zbx911** [eunomia-bpf/eunomia-bpf#23]
提几点建议:
1.编写linux 内核模块例子，直接内核模式进行io；
2.将eunomia-bpf作为系统的一个子功能，本地启动服务器接受远程编译ebpf二进制流进行操作，可省略很多不必要步骤；
3.以python做脚本语言，可有效衔接到很多软件上，比如:ida,numpy,x64dbg等上，python部分做windows和ubuntu的适配；
4.python dict对应到map功能上；
5.仅使用c或者c++持续开发，不要介入新兴语言，一是不稳定，二是新语言迭代太快；

**Comment by yunwei37** [comment]
谢谢您的建议！这个部分还没有尝试过如何使用，我们会先把这个 feature加入 roadmap，如果您能提供更多的参考信息就更感谢啦！

**Comment by zbx911** [comment]
> 谢谢您的建议！这个部分还没有尝试过如何使用，我们会先把这个 feature加入 roadmap，如果您能提供更多的参考信息就更感谢啦！

希望这个库能开发的够强

**Comment by yunwei37** [comment]
reference：

- https://source.android.google.cn/docs/core/architecture/kernel/bpf
- https://source.android.com/docs/core/datausage/ebpf-traffic-monitor
- https://android.googlesource.com/platform/external/libbpf/

eunomia-bpf 除了 libbpf 库之外没有其他大型依赖，之后应该可以尝试一下移植

**Comment by SeeFlowerX** [comment]
如果是想在安卓上体验ebpf

官方有不少现有案例，这里推荐一个simpleperf。不过看代码可以发现其中使用了不少AOSP的代码，单独自己写代码可能只能做一些简单的工作

http://aospxref.com/android-11.0.0_r21/xref/system/extras/simpleperf/

![image](https://user-images.githubusercontent.com/70688581/193735336-a475e72d-9bfa-41be-8009-f2601631b313.png)

ecapture也针对安卓进行了适配，基于go写的，灵活性还可以

https://github.com/ehids/ecapture

另外就是自己基于现有的成熟框架bcc编写eBPF程序，我测试还是很稳定的，但是对测试机要求比较高，比如开箱即用可能得上Pixel 6，否则需要自行patch内核

系列文章：https://blog.seeflower.dev/category/eBPF/

测试demo：https://pastebin.com/whcLtRAx

**Comment by zbx911** [comment]
> 如果是想在安卓上体验ebpf
> 
> 官方有不少现有案例，这里推荐一个simpleperf。不过看代码可以发现其中使用了不少AOSP的代码，单独自己写代码可能只能做一些简单的工作
> 
> http://aospxref.com/android-11.0.0_r21/xref/system/extras/simpleperf/
> 
> ![image](https://user-images.githubusercontent.com/70688581/193735336-a475e72d-9bfa-41be-8009-f2601631b313.png)
> 
> ecapture也针对安卓进行了适配，基于go写的，灵活性还可以
> 
> https://github.com/ehids/ecapture
> 
> 另外就是自己基于现有的成熟框架bcc编写eBPF程序，我测试还是很稳定的，但是对测试机要求比较高，比如开箱即用可能得上Pixel 6，否则需要自行patch内核
> 
> 系列文章：https://blog.seeflower.dev/category/eBPF/
> 
> 测试demo：https://pastebin.com/whcLtRAx

需要的money比较多

**Comment by SeeFlowerX** [comment]
做了一点测试，供参考

---

尝试在安卓Pixel 6上使用chroot编译，环境配置好之后`eunomia-bpf`和`ecli`都能编译出来

编译`eunomia-exporter`失败

chroot配置参考 => https://blog.seeflower.dev/archives/138/

环境准备参考[build.md](https://github.com/eunomia-bpf/eunomia-bpf/blob/master/documents/build.md)即可，但是chroot里面没有pkg-config，所以要手动安装下pkg-config

有几处需要修改

第一个是`ewasm/CMakeLists.txt`里面的`WAMR_BUILD_TARGET`应该改为`AARCH64`

第二个是下面这个位置应该改成`MMAP_MAP_32BIT`，看起来是第三方库的问题

```bash
/root/eunomia-bpf/third_party/wasm-micro-runtime/core/shared/platform/common/posix/posix_memmap.c:74:22: error: 'MAP_32BIT' undeclared (first use in this function); did you mean 'MMAP_MAP_32BIT'?
   74 |         map_flags |= MAP_32BIT;
      |                      ^~~~~~~~~
      |                      MMAP_MAP_32BIT
```

上面这两个地方修改之后应该就能正常编译`eunomia-bpf`和`ecli`

然后是编译`eunomia-exporter`，这个需要安装rust，按官方的方案安装最新版即可

然后会遇到一个定义问题，虽然没写过rust，但是这个应该就是`eunomia-bpf`代码本身写错了

```bash
error[E0308]: mismatched types
  --> src/bindings.rs:69:52
   |
69 |             unsafe { create_ebpf_program_from_json(json_data.as_bytes().as_ptr() as *const i8) };
   |                      ----------------------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
   |                      |
   |                      arguments to this function are incorrect
   |
   = note: expected raw pointer `*const u8`
              found raw pointer `*const i8`
note: function defined here
  --> /root/eunomia-bpf/eunomia-exporter/target/release/build/eunomia-exporter-9a287a06714970ba/out/bindings.rs:14:12
   |
14 |     pub fn create_ebpf_program_from_json(
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
```

我把`*const i8`改成了`*const u8`，然后可以接着编译，不过遇到了新的错误

看报错里面的`GLIBC`相关错误，似乎这个只能靠开发者看怎么修了，我不太懂这个

```bash
cd eunomia-exporter && cargo build --release
   Compiling eunomia-exporter v0.1.0 (/root/eunomia-bpf/eunomia-exporter)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "/tmp/rustcmD3IPo/symbols.o" ......
  = note: /usr/bin/ld: ../eunomia-bpf/build/lib/Release/libeunomia.a(eunomia_bpf.cpp.o): in function `eunomia::eunomia_ebpf_program::load_and_attach_prog()':
          eunomia_bpf.cpp:(.text+0x28): undefined reference to `libbpf_set_strict_mode'
          /usr/bin/ld: eunomia_bpf.cpp:(.text+0x34): undefined reference to `libbpf_set_print'
          /usr/bin/ld: ../eunomia-bpf/build/lib/Release/libeunomia.a(eunomia_bpf.cpp.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZSt4cerr@@GLIBCXX_3.4' which may bind externally can not be used when making a shared object; recompile with -fPIC
          /usr/bin/ld: ../eunomia-bpf/build/lib/Release/libeunomia.a(eunomia_bpf.cpp.o)(.text+0x44): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `_ZSt4cerr@@GLIBCXX_3.4'
          /usr/bin/ld: final link failed: bad value
          collect2: error: ld returned 1 exit status
          
  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `eunomia-exporter` due to previous error
make: *** [Makefile:53: eunomia-exporter] Error 101
```

不过根据文档，似乎不需要`eunomia-exporter`也是可以用的

但是由于手机内核缺少`CONFIG_DEBUG_INFO_BTF`，测试没有成功

```bash
ecli/build/bin/Release/ecli run ./eunomia-exporter/tests/package.json   
libbpf: failed to find valid kernel BTF
libbpf: Error loading vmlinux BTF: -3
libbpf: failed to load object 'client_bpf'
libbpf: failed to load BPF skeleton 'client_bpf': -3
failed to load skeleton
[2022-10-08 02:37:03.757] [error] start ebpf program failed

root@localhost:~/eunomia-bpf# file ecli/build/bin/Release/ecli
ecli/build/bin/Release/ecli: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=f8af98d9292fa807af21cb0c4fac1f3803208da2, for GNU/Linux 3.7.0, with debug_info, not stripped
```

另外看编译`package.json`都是用的docker，请问有不需要docker的方案吗？

好像自己构建`eunomia-cc`貌似也行，后面有空测试下

另外似乎`wasi-sdk`编译wasm用`ewasm`也能运行？不过wasi-sdk没有提供aarch64的预编译文件。。

**Comment by yunwei37** [comment]
> 做了一点测试，供参考

非常感谢您的帮助！

> 编译eunomia-exporter失败

看起来确实是 eunomia-exporter 有一些问题，因为最近适配 WASM module 的过程中做了一些重构的操作，还没有来得及修复 exporter，很抱歉这部分测试没有在 CI 里面写好...我会开一个新的 issue 来记录这个问题。这个 exporter 本身其实是个验证性的可观测性工具，没有它并不影响其他工具链（主要是 ecli 和 eunomia-cc）的使用

> 另外看编译package.json都是用的docker，请问有不需要docker的方案吗？

应该可以直接使用仓库本身的 Makefile 脚本来构建 package.json：
```
$ git submodule update --init --recursive       # check out libbpf and other tools
$ make
$ SOURCE_DIR=[target dir] make build
```

可以参考一下 docker file： https://github.com/eunomia-bpf/eunomia-cc/blob/master/dockerfile

**Comment by yunwei37** [comment]
用其他 SDK 编译应该问题不大，只需要有这两个函数 export 应该就好：
- bpf_main 
- process_event 

编译指令可以参考这里：https://github.com/eunomia-bpf/eunomia-bpf/tree/master/ewasm/scripts
```
# use WAMR SDK to build out the .wasm binary
/opt/wasi-sdk/bin/clang     \
        --target=wasm32 -O0 -z stack-size=4096 -Wl,--initial-memory=65536 \
        --sysroot=${WAMR_DIR}/wamr-sdk/app/libc-builtin-sysroot  \
        -I${INCLUDE_DIR} \
        -Wl,--allow-undefined-file=${WAMR_DIR}/wamr-sdk/app/libc-builtin-sysroot/share/defined-symbols.txt \
        -Wl,--strip-all,--no-entry -nostdlib \
        -Wl,--export=bpf_main \
        -Wl,--export=process_event \
        -Wl,--allow-undefined \
        -o ${OUT_FILE} ${APP_SRC}
```

**Comment by SeeFlowerX** [comment]
感谢回复，另外遇到一点新问题

编译了aarch64版的wasi-sdk之后，确实能编译出wasm

如果需要请自取，手机上编译还是相当耗时的 [wasi-sdk-16.5ga0a342ac182c-linux.tar.gz](https://gofile.io/d/hbwGAA)

但是加载的时候还行提示需要BTF的支持才可以，但是我看是生成了`vmlinux.h`的，是可以用在什么情况下吗？

```bash
./ecli/build/bin/Release/ecli run ./ewasm/test/wasm-apps/opensnoop.wasm
libbpf: failed to find valid kernel BTF
libbpf: Error loading vmlinux BTF: -3
libbpf: failed to load object 'client_bpf'
libbpf: failed to load BPF skeleton 'client_bpf': -3
failed to load skeleton
run_bpf failed -1
```

或者请问现在是否是强制要求开启下面两项才能使用

```code
CONFIG_DEBUG_INFO_BTF=y
CONFIG_DEBUG_INFO=y
```

---

另外ewasm/CMakeLists.txt#L117这个地方，有设置RUNTIME_OUTPUT_DIRECTORY，但是实际上编译的时候没有生成ewasm二进制文件

https://github.com/eunomia-bpf/eunomia-bpf/blob/76ed1b60f9b77a045bafa56f334b7cf65ee76d14/ewasm/CMakeLists.txt#L117

**Comment by yunwei37** [comment]
> 或者请问现在是否是强制要求开启下面两项才能使用

也许这些信息会有帮助：
https://github.com/eunomia-bpf/eunomia-bpf/tree/master/examples/bpftools#running-in-kernels-without-config_debug_info_btfy

目前应该还是要提供 BTF 信息才能正确重定位和启动的，之后也许可以像 eCapture 那样有一个不需要 BTF 信息的版本？ 

> 另外ewasm/CMakeLists.txt#L117这个地方，有设置RUNTIME_OUTPUT_DIRECTORY，但是实际上编译的时候没有生成ewasm二进制文件

ewasm 的二进制文件之前仅仅作为一个测试入口使用，命令行可以参考这里：
https://github.com/eunomia-bpf/eunomia-bpf/blob/master/ewasm/src/main.cpp

是否生成 ewasm 的二进制文件由这里的变量控制：
https://github.com/eunomia-bpf/eunomia-bpf/blob/76ed1b60f9b77a045bafa56f334b7cf65ee76d14/ewasm/cmake/StandardSettings.cmake#L5

也许我应该把测试的这部分入口删除掉，并且移入到单元测试里面，以免误解？

**Comment by SeeFlowerX** [comment]
感谢你的耐心回复，由于我对cmake的不了解，没有仔细阅读到这个选项的设定。

如果同样有人遇到类似的疑惑，可以通过`cmake -LAH`查看编译时可选的控制选项。

目前没有其他疑问了！

**Comment by yunwei37** [comment]
@SeeFlowerX 可以帮我们写一篇文档，关于如何在 Android 或者 arm 平台上构建现在的 eunomia-bpf 库吗？类似 #38 描述的一样，在 documents/build-arm.md 或者 build-android.md 里面描述一下你的工作，记录一下遇到的问题就好，这样之后其他人可以继续尝试。中文或者英文都行...非常感谢啦！或者其他人愿意帮忙写个文档也非常欢迎

**Comment by SeeFlowerX** [comment]
已经补充构建指南，不过目前的问题是存在BTF限制，不知道是否有这方面的修改，比如构建时提供特定的内核头文件？

**Comment by yunwei37** [comment]
非常感谢！如果您有空的话其实可以提个 pr 把它放到 documents 里面去，不过要是没空也没关系啦 :）

目前还没有完成进一步的修改，不过这段时间应该会有人做一些尝试

**Comment by yunwei37** [comment]
See the document in https://github.com/eunomia-bpf/bpf-developer-tutorial/blob/main/src/22-android/README.md

**Comment by SeeFlowerX** [comment]
很高兴看到eunomia-bpf的完善！

core还可以参考btfhub的方法，我也做了尝试是可以的

https://github.com/SeeFlowerX/BTFHubForAndroid
