### ISSUE TITLE
Failed to run docker for aarch64 platform

### ISSUE THREAD

**Issue by ChenhuiZhang** [eunomia-bpf/eunomia-bpf#239]
I try to build a simple demo in my machine:

```
$ docker run -it -v `pwd`/:/src/ ghcr.io/eunomia-bpf/ecc-x86_64:latest
ls: cannot access '/src/*.h': No such file or directory
export PATH=ATH:~/.eunomia/bin
Compiling bpf object...
Packing ebpf object and config into /src/package.json...
```
It works, but then I want to cross build the same file for aarch64:

```
$ docker run -it -v `pwd`/:/src/ ghcr.io/eunomia-bpf/ecc-aarch64:latest
Unable to find image 'ghcr.io/eunomia-bpf/ecc-aarch64:latest' locally
latest: Pulling from eunomia-bpf/ecc-aarch64
docker: no matching manifest for linux/amd64 in the manifest list entries.
See 'docker run --help'.
```

Do you know why? I saw the README mentioned the docker command support both x86_64 and aarch64, so I guess this should work?

Best Regards,
Hermes

**Comment by Officeyutong** [comment]
`aarch64` images can only be run on aarch64 machines

**Comment by Officeyutong** [comment]
`aarch64` images can only be run on aarch64 machines. If you'd like to emulation, see https://github.com/docker/buildx#building-multi-platform-images for details
