### ISSUE TITLE
Rename `ecc` and `ecli`, or not?

### ISSUE THREAD

**Issue by Officeyutong** [eunomia-bpf/eunomia-bpf#240]
Discuss whether to rename `ecc` and `ecli`.

Pros:
- Avoid conflict with existing crates.io packages
- More meaningful name (e.g, `eunomia-cc` or `eucc`)

Cons:
- To be discussed

**Comment by yunwei37** [comment]
I don't think it's necessary now because

1. We have lots of blogs and documents in numbers of platforms, using ecc and ecli. They can't be modify. For compatible reasons, it's not good to change the command name.
