### ISSUE TITLE
[FEATURE] Reconstruct code related to btfhub

### ISSUE THREAD

**Issue by Officeyutong** [eunomia-bpf/eunomia-bpf#244]
Related issue:
- #208 

We should design a new way to store, management, and package the archives fetched from btfhub. This issue will be used to discuss this

**Comment by Officeyutong** [comment]
Some ideas I have:
- Let's call `~/.eunomia` as `$EUNOMIA_HOME`
- On the ecc side, `$EUNOMIA_HOME/btfhub` will be used to cache the btf archives downloaded from btfhub. User of `ecc` can specify cache everything from btfhub, or cache only the kernel versions they need
- ecc will also have the ability to tailor and strip the btf archives in `$EUNOMIA_HOME/btfhub`, and package the archives the user want into a tar archive, along with user's ebpf program, to make the program can be easily run on multiple kernel versions without native btf support
- Currently only the tar archive of ecc's ebpf package format support btfhub. 
- `bpf-loader-rs` should have the ability to unpack the tar archive, put the btf archive containing in it to the temporary directory, and select the btf archive corresponds to the running kernel to be used for libbpf's loading

The tar archive should have the following structure
```plain
|- package.json
|- btfhub-archive
|- ---- ubuntu <ID in os-release>
|- ---- ---- 22.04 <VERSION in os-release>
|- ---- ---- ---- x86_64 <machine in uname>
|- ---- ---- ---- ---- 5.15.0-71-generic.btf <kernel-release in uname>

**Comment by yunwei37** [comment]
LGTM

**Comment by yunwei37** [comment]
The new repo can be in https://github.com/eunomia-bpf/bpf-compatible
