### ISSUE TITLE
[BUG] Package json link in readme file is incorrect

### ISSUE THREAD

**Issue by TommyLike** [eunomia-bpf/eunomia-bpf#253]
**Describe the bug**
check the link below:

https://eunomia-bpf.github.io/eunomia-bpf/sigsnoop/package.json 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

* OS: [e.g. Windows]
* Version [e.g. 10]

**Additional context**

**Comment by ocfox** [comment]
Tested and this link is working.

**Comment by TommyLike** [comment]
> Tested and this link is working.

Yeah, worked again, free feel to close this.
