### ISSUE TITLE
[BUG] I am using Docker to run it, but I encountered an error during the execution.

### ISSUE THREAD

**Issue by fengzx33** [eunomia-bpf/eunomia-bpf#254]
**Describe the bug**

![image](https://github.com/eunomia-bpf/eunomia-bpf/assets/86900797/47c2a4c5-2bd3-44dc-b265-6270e7bdaa20)

**To Reproduce**

**Expected behavior**

It can run normally.

**Screenshots**

**Desktop (please complete the following information):**

* OS: [e.g. Windows]
* Version [e.g. 10]

**Additional context**

**Comment by fengzx33** [comment]
Linux localhost.localdomain 5.10.134-13.1.an8.x86_64 #1 SMP Mon Feb 6 14:44:24 CST 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Officeyutong** [comment]
It's my fault. I've made a fix at #257

**Comment by fengzx33** [comment]
![image](https://github.com/eunomia-bpf/eunomia-bpf/assets/86900797/8440c04d-75c1-41f7-8126-038e127e50f8)

As shown in the diagram, I encountered an error when using the modified Docker to compile, but it compiled successfully when using the command line. Could you please let me know if there are any restrictions or considerations that I might have overlooked?

**Comment by Officeyutong** [comment]
> ![image](https://user-images.githubusercontent.com/86900797/245101306-8440c04d-75c1-41f7-8126-038e127e50f8.png)
> 
> @Officeyutong As shown in the diagram, I encountered an error when using the modified Docker to compile, but it compiled successfully when using the command line. Could you please let me know if there are any restrictions or considerations that I might have overlooked?

You put too many `*.bpf.c` in the folder. As the current design, there should be one `xxx.h` and one `xxx.bpf.c` in the working directory
