### ISSUE TITLE
Error: Http("Failed to poll image from `package.json`: Invalid param: relative URL without a base")

### ISSUE THREAD

**Issue by bestgopher** [eunomia-bpf/eunomia-bpf#264]
I compiled the [hello world](https://tutorial.eunomia.dev/1-helloworld/index.html) and got a problem.

```shell
[root@k8s-node2 ebpf]# ls
hello.bpf.c
[root@k8s-node2 ebpf]# docker run -it -v `pwd`/:/src/ yunwei37/ebpm:latest
ls: cannot access '/src/*.h': No such file or directory
export PATH=ATH:~/.eunomia/bin
Compiling bpf object...
Packing ebpf object and config into /src/package.json...
[root@k8s-node2 ebpf]# sudo ecli run package.json
Error: Http("Failed to poll image from `package.json`: Invalid param: relative URL without a base")
```

```shell
[root@k8s-node2 ebpf]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
```

**Comment by bestgopher** [comment]
> I can't reproduce your issue, could you please check whether the file `package.json` exists in your working directory?

Maybe the docker image and ecli  are out of time. Could you update it?

**Comment by Officeyutong** [comment]
> > I can't reproduce your issue, could you please check whether the file `package.json` exists in your working directory?
> 
> Maybe the docker image and ecli are out of time. Could you update it?

I've upadted it. Please get `ecli` from https://github.com/eunomia-bpf/eunomia-bpf/releases/tag/v0.3.52 and retry. Thank you!

**Comment by Officeyutong** [comment]
> 



> > > > I can't reproduce your issue, could you please check whether the file `package.json` exists in your working directory?
> > > 
> > > 
> > > Maybe the docker image and ecli are out of time. Could you update it?
> > 
> > 
> > I've upadted it. Please get `ecli` from https://github.com/eunomia-bpf/eunomia-bpf/releases/tag/v0.3.52 and retry. Thank you!
> 
> Did you update the docker image yunwei37/ebpm:latest

That image is obsoleted, please use `ghcr.io/eunomia-bpf/ecc-x86_64:latest` instead. Thank you!

**Comment by bestgopher** [comment]
> > > > > I can't reproduce your issue, could you please check whether the file `package.json` exists in your working directory?
> > > > 
> > > > 
> > > > Maybe the docker image and ecli are out of time. Could you update it?
> > > 
> > > 
> > > I've upadted it. Please get `ecli` from https://github.com/eunomia-bpf/eunomia-bpf/releases/tag/v0.3.52 and retry. Thank you!
> > 
> > 
> > Did you update the docker image yunwei37/ebpm:latest
> 
> That image is obsoleted, please use `ghcr.io/eunomia-bpf/ecc-x86_64:latest` instead. Thank y
