### ISSUE TITLE
[FEATURE] add support for arm 

### ISSUE THREAD

**Issue by ZhaoHaoRu** [eunomia-bpf/eunomia-bpf#275]
**Is your feature request related to a problem? Please describe.**
I tried to use eunomia-bpf in my linux (ubuntu22.04) virtual machine which built on macbook m1. But when I tried to run the command `./ecli -h`, I got  `1: Syntax error: "(" unexpected`, but when I tried this command on the server which is X86_64 architecture, the command ran successfully.

**Describe the solution you'd like**
I'm sorry I don't know how to handle this problem, perhaps the developers need to add more support.

**Provide usage examples**
The arm architecture is becoming more and more popular, I think support for arm is a goog idea.

**Comment by oluceps** [comment]
Where did you get the binary? Afaik `eunomia-bpf` supports aarch64. 
Perhaps you would like to try the `master` branch?

**Comment by ZhaoHaoRu** [comment]
I download the binary according to the guide in `README`: `wget https://aka.pw/bpf-ecli -O ecli && chmod +x ./ecli`

**Comment by Officeyutong** [comment]
> I download the binary according to the guide in `README`: `wget https://aka.pw/bpf-ecli -O ecli && chmod +x ./ecli`

It's sorry that we haven't released aarch64 binaries now. We plan to release them once we are able to cross build them (see #277 ).  Currently you can try build them manually (through `cargo install ecc-rs` or `cargo install ecli-rs`)

**Comment by Officeyutong** [comment]
#281 will fix this
