### ISSUE TITLE
怎么下载aarch64版本的ecc和ecli

### ISSUE THREAD

**Issue by Gavin0210** [eunomia-bpf/eunomia-bpf#278]
docker pull ghcr.io/eunomia-bpf/ecc-aarch64:latest
latest: Pulling from eunomia-bpf/ecc-aarch64
no matching manifest for linux/amd64 in the manifest list entriesdocker pull ghcr.io/eunomia-bpf/ecc-aarch64:latest
想要在Android中运行.

**Comment by Officeyutong** [comment]
Currently we haven't release pre-built binaries of ecc or ecli. We are working for this (see #277 for details). You can build them manually now through `cargo install`

**Comment by Officeyutong** [comment]
Update:
We have published aarch64 images. You can use `docker run -it -v `pwd`/:/src/ ghcr.io/eunomia-bpf/ecc-aarch64:latest` to run that on an aarch64 machine, or use `docker run --platform linux/arm64 -it -v `pwd`/:/src/ ghcr.io/eunomia-bpf/ecc-aarch64:latest` to run it on a non-aarch64 machine (qemu required)

**Comment by Officeyutong** [comment]
#281 will fix this
