### ISSUE TITLE
[BUG]unrecognized subcommand 'run'

### ISSUE THREAD

**Issue by jokerwenxiao** [eunomia-bpf/eunomia-bpf#327]
**Describe the bug**
I execute script `./ecli run package.json`，then occur  `error:unrecognized subcommand 'run'`

ecli version：
[ecli-http-only-macos-latest-v1.0.19.zip](https://github.com/eunomia-bpf/eunomia-bpf/releases/download/v1.0.19/ecli-http-only-macos-latest-v1.0.19.zip)

my test environment：
M1(arm64) macOS

**Comment by Officeyutong** [comment]
You are using http client of ecli, which doesn't support run native programs. use full client instead

**Comment by Officeyutong** [comment]
You are using ecli remote client, which doesn't support running native programs (`ecli run`), you may run programs remotely (`ecli client run`)

**Comment by yunwei37** [comment]
You can try the ecli from  https://github.com/eunomia-bpf/eunomia-bpf/releases/download/v1.0.20/ecli-aarch64

By the way, macos might run failed because the. Kernel doesn't have eBPF support.
