### ISSUE TITLE
[BUG] ecc report error "open dir error: No such file or directory"

### ISSUE THREAD

**Issue by baikaishiuc** [eunomia-bpf/eunomia-bpf#334]
**Describe the bug**
ecc report error "open dir error: No such file or directory"

But I think the right behavior is print help information

**To Reproduce**

Machine: m2-max
Arch: arm64
OS: parallels ubuntu 22.04

Download ecc and ecli, execute in shell

./ecc --help

**Expected behavior**
Print help information

**Screenshots**
![image](https://github.com/eunomia-bpf/eunomia-bpf/assets/618485/119b8fb0-9c79-4f97-b0e6-bcc8cb373918)

**Comment by yunwei37** [comment]
please try https://github.com/eunomia-bpf/eunomia-bpf/releases/download/v1.0.20/ecc-aarch64

**Comment by baikaishiuc** [comment]
> There are arm64 alternative releases for ecc and ecli, maybe you can try them?
> 
> Would you mind helping us update the documents for that?

好，我看看

**Comment by baikaishiuc** [comment]
> There are arm64 alternative releases for ecc and ecli, maybe you can try them?
> 
> Would you mind helping us update the documents for that?

已经提了，但是我对你文档的格式可能不是很了解，需要你在调整下

https://github.com/eunomia-bpf/bpf-developer-tutorial/pull/100
