### ISSUE TITLE
[BUG] Error: Failed to run native eBPF program

### ISSUE THREAD

**Issue by baikaishiuc** [eunomia-bpf/eunomia-bpf#335]
```
# ecli run package.json
Error: Failed to run native eBPF program

Caused by:
    Bpf error: Failed to start polling: Bpf("Failed to build skeleton: All ways tried to find vmlinux BTF, but not found. Please provide the vmlinux btf using env `BTF_FILE_PATH`. (Tried parameter `btf_archive_path`, BTF_FILE_PATH, and /sys/kernel/btf/vmlinux)"), RecvError


```

filter linux kernel config BTF
```
pc:~/source/eunomia-bpf/examples/bpftools/minimal$ cat /boot/config-5.4.18-85-generic | grep BTF
CONFIG_VIDEO_SONY_BTF_MPX=m
# CONFIG_DEBUG_INFO_BTF is not set
```

May I ask if enabling CONFIG_DEBUG_INFO_BTF and CONFIG_DEBUG_INFO_BTF_MODULES in the kernel would suffice to fix this issue ？ 

Is there a requirement for the kernel version? Would kernel version 5.4.18 be acceptable?

**Comment by Officeyutong** [comment]
Enabling CONFIG_DEBUG_INFO_BTF and recompiling kernel is a relatively easier way

**Comment by baikaishiuc** [comment]
> Enabling CONFIG_DEBUG_INFO_BTF and recompiling kernel is a relatively easier way

thank you
