### ISSUE TITLE
[FEATURE] Add document about how to build ecli and others on Arm or Android, and without BTF info

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/eunomia-bpf#38]
**Is your feature request related to a problem? Please describe.**

ecli should work on both arm, x86 and other plaform with the same package.json or app.wasm. You can refer to #23 for details.

**Describe the solution you'd like**

We need a document describe how to build it in `documents` dir. Maybe you can name it `documents/build-arm` or build-android?

**Provide usage examples**

If you can test with ecli on arm, this should be best:

```
sudo ./ecli run package.json
```

If not, that's ok. You can help us add the documents on how to build first.

**Comment by SeeFlowerX** [comment]
# Build on Android

1. install termux

https://github.com/termux/termux-app/releases/tag/v0.118.0

2. install proot-distro

select debian distro

```bash
pkg install proot-distro
proot-distro install debian
proot-distro login debian
```

3. install packages

remember `proot-distro login debian` first

```bash
apk update
apt install clang cmake libelf1 libelf-dev zlib1g-dev
```

4. sync eunomia-bpf source code

```bash
git clone https://github.com/eunomia-bpf/eunomia-bpf.git
cd eunomia-bpf
git submodule update --init --recursive
```

5. set `PKG_CONFIG_PATH` environment variable

```bash
export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
```

6. modify `ewasm/CMakeLists.txt` `WAMR_BUILD_TARGET` setting

change `set (WAMR_BUILD_TARGET "X86_64")` to `set (WAMR_BUILD_TARGET "AARCH64")`

7. build eunomia-bpf and ecli

```bash
make eunomia-bpf
make ecli
```

8. check output

`ecli` binary

- phone full path
    - /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/debian/root/eunomia-bpf/ecli/build/bin/Release/ecli
- proot-distro full path
    - /root/eunomia-bpf/ecli/build/bin/Release/ecli

and ecli file info should be like this

```bash
root@localhost:~/eunomia-bpf# file ecli/build/bin/Release/ecli
ecli/build/bin/Release/ecli: ELF executable, 64-bit LSB arm64, dynamic (/lib/ld-linux-aarch64.so.1), BuildID=f278cb3bce8ff3934201d2112a4e741061c5978a, not stripped
```

# Usage on Android

wait

**Comment by yunwei37** [comment]
Thank you very much!

**Comment by FoxVolant** [comment]
Build on Arm

/assign

**Comment by yunwei37** [comment]
Maybe we can refer to this repo: https://github.com/libbpf/libbpf-bootstrap

If this can be build in android or linux, then we can

**Comment by yunwei37** [comment]
Test on arm and run without BTF info success, and some new documents maybe updated soon.

**Comment by FoxVolant** [comment]
### Build on ARM

 步骤和在Android上类似

1.确认内核BTF选项已经打开

```
CONFIG_DEBUG_INFO=y
CONFIG_DEBUG_INFO_BTF=y
```

2.确认当前内核BTF信息可用

（1）若/sys/kernel/btf/vmlinux存在，则可通过bpftool生成vmlinux.h

```
 apt install linux-tools-(uname -r)-generic
 apt install linux-tools-generic
 bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
```

（2）若/sys/kernel/btf/vmlinux不存在，通过[[btfhub](https://github.com/aquasecurity/btfhub)](https://github.com/aquasecurity/btfhub)添加外源BTF信息或生成当前内核的定制化BTF信息

（a）添加外源BTF信息

参考 [[BTFgen tool to create smaller BTF files](https://github.com/aquasecurity/btfhub/blob/main/docs/generating-tailored-btfs.md)](https://github.com/aquasecurity/btfhub/blob/main/docs/generating-tailored-btfs.md)

```
$ git clone git@github.com:aquasecurity/btfhub.git
$ git clone git@github.com:aquasecurity/btfhub-archive.git
$ cd btfhub ; ls
//将克隆的归档文件放入 btfhub 目录
$ rsync -avz ../btfhub-archive/ --exclude=.git* --exclude=README.md ./archive/
//生成定制的 eBPF 对象的 BTF 文件:
$ ./tools/btfgen.sh -a AARCH64 -o $HOME/tracee.bpf.core.o
```

检查定制的新生成的 BTF 文件及其尺寸

```
$ find custom-archive | grep ubuntu | tail -10
$ls -lah custom-archive/ubuntu/20.04/x86_64/5.8.0-1041-azure.btf
```

（b）生成当前内核的定制化BTF信息

导入 BTFhub-Archive 存储库的未压缩的完整 BTF 文件

```
$ sudo ./example-static
$ sudo ./example-c-static
$ sudo EXAMPLE_BTF_FILE=5.8.0-63-generic.btf ./example-static
$ sudo EXAMPLE_BTF_FILE=5.8.0-63-generic.btf ./example-c-static
```

3.同步 eunomia-bpf 到本地

```
git clone https://github.com/eunomia-bpf/eunomia-bpf.git
cd eunomia-bpf
git submodule update --init --recursive
```

4.配置环境变量

```
export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
```

5.安装依赖

```
apk update
apt install clang cmake libelf1 libelf-dev zlib1g-dev
```

6.修改ewasm/CMakeLists.txt` 中的 `WAMR_BUILD_TARGET

change `set (WAMR_BUILD_TARGET "X86_64")` to `set (WAMR_BUILD_TARGET "AARCH64")`

7.编译

```
make eunomia-bpf
make ecli
```

8.检查输出

```
root@localhost:~/eunomia-bpf# file ecli/build/bin/Release/ecli
ecli/build/bin/Release/ecli: ELF executable, 64-bit LSB arm64, dynamic (/lib/ld-linux-aarch64.so.1), BuildID=f278cb3bce8ff3934201d2112a4e741061c5978a, not stripped
```

**Comment by yunwei37** [comment]
关于如何构建的 issue 应该可以关掉了，目前如果目标机器上没有 BTF 信息的话还是需要补充一下 BTF 信息，要么重新编译内核并且开启 BTF 信息选项，要么尝试从 debug 信息生成/从 BTFhub 下载对应的 BTF 信息包。

具体的文档在这里：https://github.com/eunomia-bpf/eunomia-bpf/blob/master/documents/build%20on%20Android%20or%20ARM.md

之后会考虑使用没有 BTF 信息的版本。

**Comment by df13954** [comment]
> # Build on Android
> 1. install termux
> 
> https://github.com/termux/termux-app/releases/tag/v0.118.0
> 
> 2. install proot-distro
> 
> select debian distro
> 
> ```shell
> pkg install proot-distro
> proot-distro install debian
> proot-distro login debian
> ```
> 
> 3. install packages
> 
> remember `proot-distro login debian` first
> 
> ```shell
> apk update
> apt install clang cmake libelf1 libelf-dev zlib1g-dev
> ```
> 
> 4. sync eunomia-bpf source code
> 
> ```shell
> git clone https://github.com/eunomia-bpf/eunomia-bpf.git
> cd eunomia-bpf
> git submodule update --init --recursive
> ```
> 
> 5. set `PKG_CONFIG_PATH` environment variable
> 
> ```shell
> export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
> ```
> 
> 6. modify `ewasm/CMakeLists.txt` `WAMR_BUILD_TARGET` setting
> 
> change `set (WAMR_BUILD_TARGET "X86_64")` to `set (WAMR_BUILD_TARGET "AARCH64")`
> 
> 7. build eunomia-bpf and ecli
> 
> ```shell
> make eunomia-bpf
> make ecli
> ```
> 
> 8. check output
> 
> `ecli` binary
> 
> * phone full path
>   
>   * /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/debian/root/eunomia-bpf/ecli/build/bin/Release/ecli
> * proot-distro full path
>   
>   * /root/eunomia-bpf/ecli/build/bin/Release/ecli
> 
> and ecli file info should be like this
> 
> ```shell
> root@localhost:~/eunomia-bpf# file ecli/build/bin/Release/ecli
> ecli/build/bin/Release/ecli: ELF executable, 64-bit LSB arm64, dynamic (/lib/ld-linux-aarch64.so.1), BuildID=f278cb3bce8ff3934201d2112a4e741061c5978a, not stripped
> ```
> 
> # Usage on Android
> wait

你好，6.修改ewasm/CMakeLists.txt中的WAMR_BUILD_TARGET，这个ewasm具体位置是哪里呢？
