### ISSUE TITLE
[FEATURE] Add wasm module OCI compatible command to ecli

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/eunomia-bpf#47]
类似 Bumblebee 的那种方式，不过是把 wasm 变成 OCI 镜像： https://bumblebee.io/EN

ORAS 在这里，可以用类似的方案搭建存储库：https://oras.land/ （不过存储库应该不用我们搭，只需要用他们的 client 库就好）

一个可能的 WASM 到 OCI 镜像存储的命令行工具的例子：https://github.com/engineerd/wasm-to-oci

可以尝试把 wasm 推到 Github Package 里面：https://github.com/features/packages

**Comment by yunwei37** [comment]
这部分功能需要集成到 ecli 里面去，在 ecli 里面添加一个子命令好了

**Comment by qq906907952** [comment]
添加 login 和 logout 命令
