### ISSUE TITLE
[FEATURE] using wasm-c-api for wasm runtime

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/eunomia-bpf#56]
**Is your feature request related to a problem? Please describe.**

currently we use [wamr](https://github.com/bytecodealliance/wasm-micro-runtime) as a runtime in ecli:

> WebAssembly Micro Runtime (WAMR) is a lightweight standalone WebAssembly (WASM) runtime with small footprint, high performance and highly configurable features for applications cross from embedded, IoT, edge to Trusted Execution Environment (TEE), smart contract, cloud native and so on. 

see https://github.com/WebAssembly/wasm-c-api :

- The Provide a "black box" API for embedding a Wasm engine in other C/C++ applications.
- Allow creation of bindings for other languages through typical C foreign function interfaces.

You should replace origin wamr api implement in https://github.com/eunomia-bpf/eunomia-bpf/blob/master/ewasm/src/ewasm.cpp with wasm-c-api.

refer to https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/samples/wasm-c-api in wamr.

**Provide usage examples**

```sh
$ sudo ./ecli run app.wasm
```

see also:

[Docker 发布集成 WebAssembly 的首个技术预览版](https://www.oschina.net/news/215236/docker-wasm-technical-preview)

**Comment by try-agaaain** [comment]
是不是需要将`eunomia-bpf/wasm-runtime/src/ewasm.cpp`中使用`第三方库wasm-micro-runtime`的实现方式，改用`wasm-c-api库`来实现；

替换后需要将项目下的`eunomia-bpf/third_party/wasm-micro-runtime`删除吗？

**Comment by yunwei37** [comment]
前面一个问题，是的，应该需要使用 wasm-c-api 来替换原先和 wamr 这个运行时相关的 api；

后面一个问题，不是，还是需要 wamr 的，只是改用 wasm-c-api 调用 wamr，链接的时候应该也需要链接 wamr 的 vmlib，具体可以参考 wamr 的文档

**Comment by try-agaaain** [comment]
ewasm的许多代码似乎都需要重写，重写后ewasm.cpp中提供的函数接口应该要保持不变。

对比`wasm-micro-runtime`提供的函数接口和`wasm-c-api`，两者看上去差异挺大的，实现的过程中有没有需要注意的地方呀

**Comment by yunwei37** [comment]
目前这个文件里面的代码其实也不多，做的就是两件事: 从 wasm 传递数据到 host 的 cpp 代码，从 host 传递数据到 wasm 模块，用 wasm-c-api 完成这两个部分就好。

主要就是希望看看 wasm-c-api 能不能符合我们的需求，即有一套和具体的 runtime 无关的 host api，来运行 ebpf 程序。这部分我也没试验过 wasm-c-api，所以需要你来试试能不能达成我们的目的。把这个完成之后，比如我们想把运行时从 wamr 切换到 wasmtime，应该就会方便很多啦

另外，在 #107 里面对 wasm runtime 有一点修改，我应该会先把那个 pr 合并一下，你可以接着那个 pr 的分支继续做?

**Comment by yunwei37** [comment]
目前和 wasm 模块交互的那几个函数的接口暂时保持不变，不过我们会在 #99 这个 issue 实现的时候往里面添加更多很多的 api，来实现更完善的 ebpf 和 wasm 交互的功能。这个应该会在你这个 issue 搞定之后开始做

**Comment by yunwei37** [comment]
Done by refacor wasm-bpf.
