### ISSUE TITLE
[FEATURE] Fix eunomia-cc CI and docker image

### ISSUE THREAD

**Issue by yunwei37** [eunomia-bpf/eunomia-bpf#58]
**Is your feature request related to a problem? Please describe.**

After refactor eunomia-cc in this repo, the origin docker file is broken. We need to fix it.

The CI is also not working for eunomia-cc, you can create a file for eunomia-cc in .github dir.

Running new eunomia-cc without docker:

Makefile build the toolchain:

```shell
git submodule update --init --recursive       # check out libbpf
cd eunomia-cc
make
export PATH=$PATH:~/.eunomia/bin
```

After the toolchain has been build and installed, run this command to compile a json and object in eunomia-cc dir:

```shell
ecc cmd/test/client.bpf.c cmd/test/event.h
```

see https://github.com/eunomia-bpf/eunomia-bpf/tree/master/eunomia-cc for details. 

You may need to install Rust toolchain to compile eunomia-cc binary:

```sh
curl https://sh.rustup.rs -sSf | sh
```

You can test ecc with:

```sh
cd eunomia-cc
cd cmd
cargo test
```

**Describe the solution you'd like**

- [ ] add a workflow to build and test eunomia-cc, similar to https://github.com/eunomia-bpf/eunomia-bpf/blob/master/.github/workflows/exporter.yml.
- [ ] fix the docker image here: https://github.com/eunomia-bpf/eunomia-bpf/blob/master/eunomia-cc/dockerfile .Please make the docker image as small as possible.

**Comment by GorilaMond** [comment]
I could try to fix the docker image.

**Comment by yunwei37** [comment]
This is finished now.
